version: "3.9"

services:
  myapp:
    build: .
    container_name: myapp
    ports:
      - "8000:8000"
    environment:
      github_webhook_secret: "${GITHUB_WEBHOOK_SECRET}"
      GEMINI_API_KEY: "${GEMINI_API_KEY}"
      APP_ID: "${APP_ID}"
      APP_PRIVATE_KEY: "${APP_PRIVATE_KEY}"
      APP_PRIVATE_KEY_path: "${APP_PRIVATE_KEY_PATH}"
    restart: always
